### ISSUE TITLE
JSONObject["game_id"] is not an int.

### ISSUE THREAD

**Issue by Sponges** [NotGGhost/jDiscord#10]
Discord logged in
org.json.JSONException: JSONObject["game_id"] is not an int.
	at org.json.JSONObject.getInt(JSONObject.java:609)
	at me.itsghost.jdiscord.internal.request.poll.ReadyPoll.updateOnlineStatus(ReadyPoll.java:133)
	at me.itsghost.jdiscord.internal.request.poll.ReadyPoll.setupServers(ReadyPoll.java:172)
	at me.itsghost.jdiscord.internal.request.poll.ReadyPoll.process(ReadyPoll.java:57)
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:66)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at me.itsghost.jdiscord.internal.request.poll.TypingPoll.process(TypingPoll.java:33)
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:89)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at me.itsghost.jdiscord.internal.request.poll.MessagePoll.process(MessagePoll.java:48)
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:83)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at me.itsghost.jdiscord.internal.request.poll.TypingPoll.process(TypingPoll.java:33)
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:89)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at me.itsghost.jdiscord.internal.request.poll.TypingPoll.process(TypingPoll.java:33)
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:89)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:63)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:745)

**Comment by NotGGhost** [comment]
Try the hotfix I sent ya
