### ISSUE TITLE
"JSONObject["color"] is not an int.", and NPE every time an event triggers

### ISSUE THREAD

**Issue by hlaaftana** [NotGGhost/jDiscord#14]
http://pastebin.com/ACttYpfP

I highly doubt the fact that it's Groovy changes anything. (EDIT: Rewrote the entire thing in Java and nothing changed, still same errors)

**Comment by NotGGhost** [comment]
http://itsghost.me/jdiscord-hotfix-shaded.jar
Try that

**Comment by hlaaftana** [comment]
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
	at sun.security.util.SignatureFileVerifier.process(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarFile.initializeVerifier(Unknown Source)
	at java.util.jar.JarFile.getInputStream(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
	at sun.misc.Resource.cachedInputStream(Unknown Source)
	at sun.misc.Resource.getByteBuffer(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
