### ISSUE TITLE
org.json.JSONException: JsonArray[0] is not a JSONObject. during UserUpdatePoll

### ISSUE THREAD

**Issue by hlaaftana** [NotGGhost/jDiscord#17]
org.json.JSONException: JSONArray[0] is not a JSONObject.
        at org.json.JSONArray.getJSONObject(JSONArray.java:367)
        at me.itsghost.jdiscord.internal.request.poll.UserUpdatePoll.process(UserUpdatePoll.java:43)
        at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:113)
        at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
        at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
        at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
        at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
        at java.lang.Thread.run(Unknown Source)

**Comment by NotGGhost** [comment]
nei 
Try latest version
