### ISSUE TITLE
Direct Message crash

### ISSUE THREAD

**Issue by monkeymanboy** [NotGGhost/jDiscord#34]
This happens whenever the bot direct messages someone and has an onMessage

     public void userChat(UserChatEvent e) {
          String response = "test";
          if (response != "" && e.getGroup() != null) {
             e.getGroup().sendMessage(response);
         } else {
             e.getUser().getUser().getGroup().sendMessage(response);
         }
     }

In any normal chat this would spam test after anyone types anything but in a DM it gives an error as soon as it puts test in the chat.

java.lang.NullPointerException
	at me.itsghost.jdiscord.internal.request.poll.MessagePoll.process(MessagePoll.java:50)
	at me.itsghost.jdiscord.internal.request.WebSocketClient.onMessage(WebSocketClient.java:92)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:312)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:368)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:157)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:230)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Unknown Source)

**Comment by NotGGhost** [comment]
Update to 2.1.2
