### ISSUE TITLE
NoClassDefFoundError on login

### ISSUE THREAD

**Issue by Gleydar** [NotGGhost/jDiscord#39]
On attempting to log in the Client, I get the following error:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/neovisionaries/ws/client/WebSocketListener
	at me.itsghost.jdiscord.internal.Login.process(Login.java:34)
	at me.itsghost.jdiscord.internal.impl.DiscordAPIImpl.login(DiscordAPIImpl.java:79)
	at me.itsghost.jdiscord.internal.impl.DiscordAPIImpl.login(DiscordAPIImpl.java:36)
	at com.gleydar.disbot.DisBot.main(DisBot.java:31)
Caused by: java.lang.ClassNotFoundException: com.neovisionaries.ws.client.WebSocketListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more`

**Comment by kuroodo** [comment]
I see that you closed this. Can you tell me what you did to resolve this?

**Comment by Gleydar** [comment]
You need to declare some other dependencies in your maven file

kuroodo <notifications@github.com> schrieb am Sa., 27. Feb. 2016 20:22:
